import type { StoreRepository } from '../../domain/repositories/StoreRepository';
import {
  createStore,
  createCategory,
  createScenario,
  createSuite,
  deleteCategory,
  deleteScenario,
  deleteStore,
  deleteSuite,
  exportStoreData,
  getStoreDetail,
  listCategories,
  listScenarios,
  listStoreSummaries,
  listSuites,
  updateCategory,
  updateScenario,
  updateStore,
  updateSuite,
} from '../external/stores';

export const firebaseStoreRepository: StoreRepository = {
  listSummary: listStoreSummaries,
  getDetail: getStoreDetail,
  create: createStore,
  update: updateStore,
  delete: deleteStore,
  listScenarios,
  createScenario,
  updateScenario,
  deleteScenario,
  listSuites,
  createSuite,
  updateSuite,
  deleteSuite,
  listCategories,
  createCategory,
  updateCategory,
  deleteCategory,
  exportStore: exportStoreData,
};
