import type { EnvironmentRepository } from '../../domain/repositories/EnvironmentRepository';
import {
  addEnvironmentUser,
  copyEnvironmentAsMarkdown,
  createEnvironment,
  createEnvironmentBug,
  deleteEnvironment,
  deleteEnvironmentBug,
  listEnvironmentBugs,
  observeEnvironment,
  observeEnvironments,
  removeEnvironmentUser,
  transitionEnvironmentStatus,
  updateEnvironment,
  updateEnvironmentBug,
  updateScenarioStatus,
  uploadScenarioEvidence,
  exportEnvironmentAsPDF,
  exportEnvironmentAsExcel,
} from '../external/environments';

export const firebaseEnvironmentRepository: EnvironmentRepository = {
  create: createEnvironment,
  update: updateEnvironment,
  delete: deleteEnvironment,
  observeEnvironment,
  observeAll: observeEnvironments,
  addUser: addEnvironmentUser,
  removeUser: removeEnvironmentUser,
  updateScenarioStatus,
  uploadScenarioEvidence,
  listBugs: listEnvironmentBugs,
  createBug: createEnvironmentBug,
  updateBug: updateEnvironmentBug,
  deleteBug: deleteEnvironmentBug,
  transitionStatus: transitionEnvironmentStatus,
  exportAsPDF: exportEnvironmentAsPDF,
  exportAsExcel: exportEnvironmentAsExcel,
  copyAsMarkdown: copyEnvironmentAsMarkdown,
};
